### ISSUE TITLE
RUN en la configuracion debe ser el mismo del login

### ISSUE THREAD

**Issue by ajunge** [rmeb/prescripcion-dapp#13]
No se debiera pedir el RUN en la configuracion pues debiera ser el mismo del login

**Comment by ajunge** [comment]
En ninguna de las dos partes de la configuracion. 
Ni en "Datos del Profesional"
Ni en "Servicio de Firma"

**Comment by ocio28** [comment]
Corregido.

**Comment by ajunge** [comment]
Me explique mal. El RUN debiera mostrarse pero no debe poder editarse

**Comment by ocio28** [comment]
en los dos lugares?
en "Datos del Profesional"
en "Servicio de Firma"

**Comment by ajunge** [comment]
Sip. En ambos
