### ISSUE TITLE
editar prescripciones en fase previo a emitir

### ISSUE THREAD

**Issue by hvegax** [rmeb/prescripcion-dapp#16]
Se podrá editar las prescripciones antes de emitir la receta?

**Comment by hvegax** [comment]
![Captura de pantalla 2018-07-05 a la(s) 16.05.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3cff78e8ae280011f8694c/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726956f37a28c8b37ff2122e410e4f12fd591b4654fdff972ba3a83f74984019ad93320521957903a6aa874dbf52bf71824880bfb9d94a95e83d24b5dd871c3c1c020a95ed1f64fecd149501bc1ea35f5fb6123169e773357c4f961f742b686624afee92.png)

**Comment by ajunge** [comment]
Se puede eliminar una que fue mal creada antes de emitir
