### ISSUE TITLE
XML prescripción en navegador

### ISSUE THREAD

**Issue by hvegax** [rmeb/prescripcion-dapp#20]
es aceptable por ESIGN que el XML quede en el nevagador del usuario?

**Comment by hvegax** [comment]
![Captura de pantalla 2018-07-23 a la(s) 18.01.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3cff78e8ae280011f8694c/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726956f37a28c8b37ff21028410e4f12fd591b4654fdf1972ba7a83e76984019ad93320521957903a6aa874dbf52bf71824880bfb9d94a95e83d24b5dd871c3c1c020a95ed1f64fecd149501bc1ea35f5fb6123169e773357e449c1d762d6e6f22aeee92.png)

**Comment by ajunge** [comment]
Es un template de XML, debiera ser publico
