### ISSUE TITLE
path de seguridad

### ISSUE THREAD

**Issue by hvegax** [rmeb/prescripcion-dapp#21]
es aceptble por seguridad esign que los path y nombres de los smart-contacts queden visibles?

**Comment by hvegax** [comment]
![Captura de pantalla 2018-07-23 a la(s) 18.02.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3cff78e8ae280011f8694c/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726956f37a28c8b37ff21028410e4f12fd591b4654fdf1972ba4a83877984019ad93320521957903a6aa874dbf52bf71824880bfb9d94a95e83d24b5dd871c3c1c020a95ed1f64fecd149501bc1ea35f5fb6123f69e773357e449c1d7624626020a8ee92.png)

**Comment by ajunge** [comment]
Si. No hay problema. El contenido de ese archivo es publico tambien
