### ISSUE TITLE
Generar y Firmar XML

### ISSUE THREAD

**Issue by ajunge** [rmeb/prescripcion-dapp#7]
Armar XML de la receta de acuerdo al formato definido y enviar a firmar al servicio de firma

**Comment by ocio28** [comment]
Necesito un usuario y clave para probar el servidor de firmas.

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns2:intercambiaDocResponse xmlns:ns2="http://ws.signserver.esign.com/">
         <intercambiaDoc>
            <IntercambiaDocResult>
               <Estado>FAIL</Estado>
               <Comentarios>Configuracion no disponible, favor verifique el nombre</Comentarios>
               <FormatoDocumento/>
               <NombreDocumento/>
               <Documento/>
            </IntercambiaDocResult>
         </intercambiaDoc>
      </ns2:intercambiaDocResponse>
   </soap:Body>
</soap:Envelope>
